bert_base_path: E:/AI/GPT-SoVITS-V3-Infer/pretrained_models/chinese-roberta-wwm-ext-large
cnhuhbert_base_path: E:/AI/GPT-SoVITS-V3-Infer/pretrained_models/chinese-hubert-base
device: cuda
is_half: true
t2s_weights_path: E:\AI\GPT-SoVITS-v3-202502123fix2\GPT_weights_v3\BiCuiSi-v3-e15.ckpt
version: v3     # 根据模型的版本设置，必须设置正确！否则会出错！
vits_weights_path: E:\AI\GPT-SoVITS-v3-202502123fix2\SoVITS_weights_v3\BiCuiSi-v3_e2_s68.pth

# t2s_weights_path: E:\AI\GPT-SoVITS-v2-240821\GPT_weights_v2\BiCuiSi-e15.ckpt
# version: v2
# vits_weights_path: E:\AI\GPT-SoVITS-v2-240821\SoVITS_weights_v2\BiCuiSi_e8_s272.pth
# t2s_weights_path: E:\AI\GPT-SoVITS-v2-240821\GPT_SoVITS\pretrained_models\s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
# version: v1
# vits_weights_path: E:\AI\GPT-SoVITS-v2-240821\GPT_SoVITS\pretrained_models\s2G488k.pth
